PREFIX wk-us:   <http://wolterskluwer.com/ceres/wk-us/>
PREFIX xl:      <http://www.w3.org/2008/05/skos-xl#>
PREFIX ltr:     <http://wolterskluwer.com/ceres/ltr-v1.0/>
PREFIX xs:      <http://www.w3.org/2001/XMLSchema#>
PREFIX wkpl:    <http://wolterskluwer.com/ceres/wk-pl/>
PREFIX wkus:    <http://wolterskluwer.com/ceres/wk-us/>
PREFIX wknl:    <http://wolterskluwer.com/ceres/wk-nl/>
PREFIX dcterms:  <http://purl.org/dc/terms/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX condor:  <http://wolterskluwer.com/ceres/condor/>
PREFIX wkde:    <http://wolterskluwer.com/ceres/wk-de/>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos-xl:  <http://www.w3.org/2008/05/skos-xl#>
PREFIX fn:      <http://www.w3.org/2005/xpath-functions#>
PREFIX dc:      <http://purl.org/dc/elements/1.1/>
PREFIX gai:     <http://wolterskluwer.com/ceres/wk-us/gai/>
PREFIX cw:      <http://wolterskluwer.com/ceres/content-warehouse-v1.0/>
PREFIX ns5:     <http://www.w3.org/2008/05/skos-xl#>
PREFIX ns6:     <http://www.w3.org/2004/02/skos/core#>
PREFIX ns2:     <http://wolterskluwer.com/ceres/condor/>
PREFIX ns1:     <http://wolterskluwer.com/ceres/content-warehouse-v1.0/>
PREFIX ns4:     <http://wolterskluwer.com/ceres/ltr-v1.0/>
PREFIX err:     <http://www.w3.org/2005/xqt-errors#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX cc:      <http://wolterskluwer.com/ceres/concept-v1.0/>
PREFIX schemarama:      <http://purl.org/net/schemarama#>
PREFIX qp:      <http://wolterskluwer.com/ceres/registered-query-parameters#>
